Update pagination documentation
quaderno/quaderno-api pull request #25
Opened 2021-03-16 15:43 UTC by JSFernandes

This PR updates the documentation with the new pagination strategy which we hope to release soon.

I was considering updating the changelog for the documentation, but it includes a lot of irrelevant Slate changes. Shall we reboot it?

2021-03-18 17:27 UTC, polimorfico requested changes

2021-03-18 17:27 UTC, polimorfico commented on source/includes/_setup.md
>  You can change the number of objects to be returned with the `limit` parameter, defaulting to `25`.
Should be set a maximum number of objects per page to avoid abuses?

2021-03-18 17:27 UTC, polimorfico commented on source/includes/_setup.md
> +> A call with the `max_id` parameter set:
It should be `starting_after`

2021-03-18 17:27 UTC, polimorfico commented on source/includes/_setup.md
> +curl https://ACCOUNT_NAME.quadernoapp.com/api/contacts.json?max_id=42 \
The name of the query string should be `starting_after`

2021-03-19 09:30 UTC, jrub commented on source/includes/_setup.md
> +curl https://ACCOUNT_NAME.quadernoapp.com/api/contacts.json?max_id=42 \
There's another reference to the `page` parameter on Line 170 we should change

2021-03-19 10:08 UTC, jrub reviewed
Added some code suggestions for unifying to "legacy" (already used in the Tax API) instead of deprecated. It could be the other way around if preferred.

Also, reviewed the changelog searching for these Slate changes you mentioned, but couldn't find any.

2021-03-19 10:08 UTC, jrub commented on source/includes/_setup.md
> +  -u YOUR_API_KEY:x
I would move this example to get it visually to the right of the legacy note, or at least change DEPRECATED to **Legacy**. Note there's a code suggestion below.

2021-03-19 11:40 UTC, JSFernandes commented on source/includes/_setup.md
>  You can change the number of objects to be returned with the `limit` parameter, defaulting to `25`.
There is, but it looks like we didn't document it. Going to add it.

2021-03-19 11:43 UTC, JSFernandes commented
@jrub The Slate changes I meant are the ones in https://github.com/quaderno/quaderno-api/blob/master/CHANGELOG.md
Version 2.7.0 was added by us and contains relevant documentation changes. Every previous version has changes related with slate infrastructure/environment/setup.

2021-03-19 12:15 UTC, polimorfico commented
@JSFernandes Feel free to remove all the content in changelog that are not related to our API.

2021-03-19 13:59 UTC, jrub commented
Oh, I see what you meant with the changelog now. We definitely need a changelog for our public API (currently `source/includes/_changelog.md`, as is used for the online dev docs), but, do we really need another for tech changes over the repo? (which I would say it's usually the use of the one on the root of an open source project)

If we do then it should be about our tech stack changes and similar, not Slate's, that is for sure.

2021-03-29 10:34 UTC, JSFernandes commented
@jrub @polimorfico Can you please take a look at the recent changes? I hope to deploy the pagination changes and this today. I will then work on updating the gem.

2021-03-29 12:22 UTC, polimorfico approved these changes
I only found a small typo. The rest is okay IMO.

2021-03-29 12:22 UTC, polimorfico commented on source/includes/_changelog.md
> +* Breaking change: record pagination is no longer performed with a `page` parameter, but with a `max_id` parameter. See the [pagination documentation](https://developers.quaderno.io/api/#pagination)
The name of the new parameter is wrong.

2021-03-29 13:38 UTC, JSFernandes commented
@polimorfico can you please merge and deploy when you have time?

2021-03-29 15:14 UTC, merged